//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.22 at 04:00:56 PM CDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2009/xmlenc11#", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.fusionauth.samlv2.domain.jaxb.w3c.xmlenc11;